### PR TITLE
Fix: Issue #18 - Migrate resources to Res.drawable (also update Kotlin & Compose)

### LINKED ISSUE #18: Migrate resources to Res.drawable
We should update Kotlin to 1.9.23, Compose to 1.6.1, and migrate resources from name based `DrawableResource("icon_name")` to statically generated `Res.drawable.icon_name`. See the [resources docs](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html).

### PR DESCRIPTION
**Pull request by b0r1ngx**
Resolving an Issue #18 

Closes #18.

## Summary by CodeRabbit

- **Refactor**
    - Enhanced the game icons structure for easier maintenance.

### CODE REVIEW

**Review by arkivanov — APPROVED** [review]

**Comment by arkivanov** [comment]
Thank you for the PR!

**Comment by b0r1ngx** [comment]
Thanks you for issue and review!

**Comment by b0r1ngx** [comment]
Arkadii, I prepared values/strings.xml in this commit, and forget to populate updates for strings, maybe its a good idea, to extract strings from code?

**Comment by arkivanov** [comment]
Yeah, we can do that!

**Pull request merged**
